name: Digest Summarizer 2

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  

jobs:
  issue-digest:
    runs-on: ubuntu-latest

    steps:
      - name: Run Issue Digest Action
        uses: Eclipse-Dominator/GithubDigest@34-remove-mentions-from-the-digest
        with:
          repo: "teammates/TEAMMATES"
          timezone: "Singapore"
