name: Digest Summarizer 2

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  

jobs:
  Run_digest: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Issue Digest Action
        uses: Eclipse-Dominator/GithubDigest@29-allow-multiple-digests-in-the-same-repo
        with:
            repo: "Eclipse-Dominator/Digest_tester"
            timezone: "Singapore"

          
