name: Digest Summarizer

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  

jobs:
  Run_digest: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Issue Digest Action
        uses: Eclipse-Dominator/GithubDigest@33-tweak-opening-message
        with:
            timezone: "Singapore"

          
